# Generated by Django 5.2.3 on 2025-07-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_date', models.DateField()),
                ('schedule_start', models.DateTimeField()),
                ('schedule_end', models.DateTimeField()),
            ],
            options={
                'db_table': 'Schedule',
                'managed': False,
            },
        ),
    ]
