# Generated by Django 5.2.3 on 2025-06-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schedule',
            table='Schedule',
        ),
    ]
