# Generated by Django 5.2.3 on 2025-06-29 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0003_alter_schedule_table'),
        ('seats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('seat_status', models.CharField(max_length=20)),
                ('schedule', models.ForeignKey(db_column='schedule_id', on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.schedule')),
                ('seat', models.ForeignKey(db_column='seat_id', on_delete=django.db.models.deletion.DO_NOTHING, to='seats.seats')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
    ]
