# Generated by Django 5.2.3 on 2025-06-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_type', models.CharField(max_length=50)),
                ('row_label', models.CharField(max_length=5)),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'Seats',
                'managed': False,
            },
        ),
    ]
