# Generated by Django 5.2.3 on 2025-06-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.AddField(
            model_name='movie',
            name='format',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX'), ('4DX', '4DX')], default='2D', help_text='Format of the movie', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(default='Unknown', help_text='Comma-separated list of genres', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.PositiveIntegerField(default=120, help_text='Length of the movie in minutes'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, help_text='Poster image of the movie', null=True, upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.TextField(default='', help_text='Link or embed code of the trailer'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(default='', help_text='Brief description of the movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(help_text='Release date of the movie'),
        ),
    ]
