# Generated by Django 5.2.3 on 2025-06-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_duration_remove_movie_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'managed': False},
        ),
    ]
