# Generated by Django 5.2.3 on 2025-07-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporarybooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarybooking',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
