# Generated by Django 5.2.3 on 2025-07-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporarybooking', '0002_temporarybooking_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarybooking',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
