# Generated by Django 5.2.3 on 2025-06-29 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capacity', models.PositiveIntegerField(help_text='Total number of seats in the room')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the room is currently active')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='cinema.cinema')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
                'ordering': ['name'],
            },
        ),
    ]
