# Generated by Django 5.2.3 on 2025-06-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'managed': False},
        ),
    ]
